### ISSUE TITLE
public access to a PublicKey's comment and options

### ISSUE THREAD

**Issue by Trolldemorted** [sdemos/openssh-keys#13]
Your PublicKey contains three members:

```
pub struct PublicKey {
    options: Option<String>,
    data: Data,
    comment: Option<String>,
}
```

We can get a copy of the data by calling `data`, but there is no way to access the other members from the outside. Would you mind public getters?

**Comment by sdemos** [comment]
Lh, that was a mistake. I meant for those to be publically accessible. Thanks for catching that!
